kind: ConfigMap
metadata:
  name:  start-lab-script
apiVersion: v1
data:
  start-script.sh: |

      OCP_API_URL={{ .Values.ocp.api_url }}
      OCP_ADMIN_USER= {{ .Values.ocp.admin_user }}
      OCP_ADMIN_PASSWORD={{ .Values.ocp.admin_password }}
      BASTION_HOST={{ .Values.bastion.host }}
      USER_COUNT={{ .Values.lab.user_count }}

      echo "Starting the lab..."
      oc login --insecure-skip-tls-verify  -u $OCP_ADMIN_USER -p $OCP_ADMIN_PASSWORD $OCP_API_URL

      for i in $(seq 1 $USER_COUNT); do

        USER_HOST=`oc get route user${i}-customers-manifests -n customers-user${i} -o jsonpath='{.status.ingress[0].host}'`
        echo "starting user${i}... at $USER_HOST"

        curl -k https://$USER_HOST/customers/JKHGFTGTYU/$BASTION_HOST &
        sleep 1

      done
      echo "All users started"

